# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'ReactInMotion'
  app.pods do
    pod 'React', '0.11.0'
    pod 'React/RCTActionSheet'
    pod 'React/RCTGeolocation'
    pod 'React/RCTImage'
    pod 'React/RCTNetwork'
    pod 'React/RCTSettings'
    pod 'React/RCTText'
    pod 'React/RCTVibration'
    pod 'React/RCTWebSocket'
  end
end
